---

- name: Create the grok_exporter group
  group:
    name: "{{ grok_exporter_system_group }}"
    state: present
    system: true

- name: Create the grok_exporter user
  user:
    name: "{{ grok_exporter_system_user }}"
    group: "{{ grok_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: true
    home: /etc/grok_exporter

- name: Download grok_exporter archive
  get_url:
    url: "{{ grok_exporter_git_url }}/releases/download/v{{ grok_exporter_version }}/grok_exporter-{{ grok_exporter_version }}.linux-amd64.zip"
    dest: "/tmp/grok_exporter-{{ grok_exporter_version }}.linux-amd64.zip"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2

- name: Propagate grok_exporter to the machine we want it installed into
  unarchive:
    src: "/tmp/grok_exporter-{{ grok_exporter_version }}.linux-amd64.zip"
    dest: "/etc"
    creates: "/etc/grok_exporter-{{ grok_exporter_version }}.linux-amd64"
    owner: "{{ grok_exporter_system_user }}"
    group: "{{ grok_exporter_system_group }}"
    remote_src: yes
  notify: restart grok_exporters

- name: Move /etc/grok_exporter-{{ grok_exporter_version }}.linux-amd64 to /etc/grok_exporter
  shell: "mv grok_exporter-{{ grok_exporter_version }}.linux-amd64/* grok_exporter && touch grok_exporter_copied_{{ grok_exporter_version }}"
  args:
    chdir: /etc
    creates: "/etc/grok_exporter_copied_{{ grok_exporter_version }}"

- name: Copy the Grok Exporter sysvinit script
  template:
    src: init.sh.j2
    dest: /etc/init.d/grok-exporter
    owner: root
    group: root
    mode: 0755

- name: Copy the Grok Exporter config file
  template:
    src: service_config.j2
    dest: "/etc/grok_exporter/{{ item.name }}.conf"
    owner: "{{ grok_exporter_system_user }}"
    group: "{{ grok_exporter_system_group }}"
    mode: 0644
  notify: restart grok_exporters
  with_items: "{{ grok_services }}"

- name: Make sure grok-exporter runs at astartup
  service:
    name: "grok-exporter"
    enabled: yes
    state: started
